# Generated by Django 4.1.1 on 2022-09-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_product_categories_delete_productcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
    ]
