# Generated by Django 4.1.1 on 2022-09-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('women', 'women'), ('men', 'men'), ('kids', 'kids'), ('accessories', 'accessories')], max_length=200),
        ),
    ]
