# Generated by Django 4.1.1 on 2022-10-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_cover_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product/product_image', verbose_name='Product Image'),
        ),
    ]
