# Generated by Django 4.1.1 on 2022-10-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_field',
            field=models.ImageField(null=True, upload_to='product/product_image', verbose_name='product images'),
        ),
    ]
